#!/bin/bash
export DJANGO_PORT=8080  # Binder often uses port 8080 for web services
export DJANGO_SETTINGS_MODULE=skeniraj_in_naroci.settings  # Replace with your project settings
export POSTGRES_PORT=443  # Optional, only if using PostgreSQL

export DB_HOST='baza.fmf.uni-lj.si'
export DB_NAME='sem2024_vitol'
export DB_USER='javnost'
export DB_PASSWORD='javnogeslo'

# Start the Django development server
python manage.py runserver 0.0.0.0:${DJANGO_PORT} &

# Execute the command passed to the script
exec "$@"